### ISSUE TITLE
Probleme avec des partages samba sans droits NT

### ISSUE THREAD

**Issue by plamaiziere** [uPortal-Project/esup-filemanager#128]
Bonjour,

Description: 

Pour les partages samba qui ne portent pas de droits étendus de type NT, il y a une exception "null pointer" lorsqu'une ressource smb n'est pas en écriture.

Dans la méthode CifsAccessImpl.resourceAsJsTreeFile, si une ressource SMB n'est pas en écriture, alors le code effectue un appel à ressource.getSecurity() pour obtenir les droits étendus (ACE), puis vérifie si dans ces ACE il y aurait une permission en écriture.
Dans le cas d'un partage sans droits étendus de type NT, il n'y a pas d'ACE, getSecurity renvoie un tableau null. Ce qui provoque l'exception.
La solution consiste à vérifier que le tableau d'ACE n'est pas nul (cf patch ci joint)

```
  CifsAccessImpl.resourceAsJsTreeFile(...)
  ...

  boolean resourceWritable = resource.canWrite();
  if (!resourceWritable) {
	  try {
		  ACE[] ACEs = resource.getSecurity();
		  for(ACE ace: ACEs) {
			  if (this.userAuthenticator.getUsername().equals(ace.getSID().getAccountName())) {
				  if ((ace.getAccessMask() & ACE.FILE_WRITE_DATA)!=0) {
					  resourceWritable = true;
					  break;
				  }
			  }
		  }
	  } catch (IOException e) {
		  log.info("Can't get ressource permissions : "+ e.getMessage());
	  }
  }
```

Patch sur la version tag 1.4.0

[0001-Do-not-check-ACE-on-ressource-without-DACL.patch.txt](https://github.com/uPortal-Project/esup-filemanager/files/11270627/0001-Do-not-check-ACE-on-ressource-without-DACL.patch.txt)

Cordialement,
Patrick Lamaizière Université de Rennes.

**Comment by jgribonvald** [comment]
Thanks @plamaiziere for the report. On an other side could you test something ?

I've on my side a change that check ACE on a more complete way as new windows system manage some things on an other way.

here is the change for ACEs check:

**Comment by plamaiziere** [comment]
Hi @jgribonvald 
Unfortunately all our shares will be changed soon without Windows NT  ACE, this is why we was hit by this issue.
So I will not be able to check this.
Regards.

**Comment by jgribonvald** [comment]
It was in case you were again able to test it...

**Comment by jgribonvald** [comment]
So fixed with #129
