### ISSUE TITLE
Full java 8 migration and Spring upgrade

### ISSUE THREAD

**Issue by jgribonvald** [uPortal-Project/esup-filemanager#66]
Hi folks I've started an upgrade of the esup-filemanager portlet.

I've just pushed a [new branch here](https://github.com/uPortal-Project/esup-filemanager/tree/WIP_java8)  (not all work finished), so please provide a feedback on use (I'm on hollydays now and won't have really more time to work on).

For testing you can:
* switch to WIP_java8 branch
 make a package locally with:
* export JAVA_HOME with java 8 link
* run mvn clean package install

and deploy it into a local uPortal install by upgrading to 4.0.1-SNAPSHOT version on gadle.properties
* go on `My Drive` portlet
* navigate on directories and try to upload/download

**Comment by jonathanmtran** [comment]
In b6794e0, the `esup` and `esup-third` repositories were removed, but it appears they are needed for the `com.googlecode.sardine:sardine` dependency as it does not exist in Maven Central and is pulled from `esup`/`esup-third`.

Once that dependency is resolved, I was able to build the portlet and deploy it to uPortal-start. From there I was able to navigate, upload, and download.

**Comment by jgribonvald** [comment]
@jonathanmtran thanks a lot ! For the esup an esup-third repositories it remains to update dependencies version, I will try to have a look on so... 
After, I don't know if I try to update the jquery version, or I let all UI part for a bigger improvisent like à WC UI.
